# Generated by Django 4.2.2 on 2023-06-15 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_upload', '0002_alter_music_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(upload_to='music/', validators=[django.core.validators.FileExtensionValidator(['mp3'])]),
        ),
    ]
