# Generated by Django 4.2.2 on 2023-06-15 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_upload', '0003_alter_music_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='allowed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
